baseURL = "https://halprez.github.io"
languageCode = "en-us"
title = "Alejandro Perez"
theme = "hugo-theme-nix"

[params]
  Name = "Alejandro Perez"
  HeaderUsername = "Alejandro Perez"
  HeaderHostname = "Alejandro Perez"
  About = "info_about_you"
  ProfilePicture = "/images/me.png"
